name: 'NativeIrisApiEngineBinding'
description: 'Bindings to IrisApiEngine'

output: 'lib/src/impl/native_iris_api_engine_bindings.dart'

headers:
  entry-points:
    - 'third_party/include/iris_rtc_c_api.h'
  include-directives:
    - 'third_party/include/iris_rtc_c_api.h'

llvm-path:
  - '/usr/local/opt/llvm'