name: 'NativeIrisApiEngineBinding'
description: 'Bindings to IrisApiEngine'

output: 'lib/src/impl/native_iris_api_engine_bindings.dart'

headers:
  entry-points:
    - 'third_party/include/iris_rtc_c_api.h'
    # - 'third_party/include/iris_fpa_flutter_c_api.h'
  include-directives:
    - 'third_party/include/iris_rtc_c_api.h'
    # - 'third_party/include/base/**'
    # - 'third_party/include/iris_fpa_flutter_c_api.h'

llvm-path:
  - '/usr/local/opt/llvm'

# Generating typedefs need set the sdk constraints to >=2.14, remove it 
# if we can set our sdk constraints to >=2.14
# typedefs:
#   exclude:
#     - 'IrisFpaProxyServicePtr'
#     - 'IrisCEventHandler'
#     - 'Func_Event'
#     - 'Func_EventWithBuffer'
#     - 'IrisEventHandlerHandle'